/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HubsIndexRouteImport } from './routes/hubs/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as ChaptersIndexRouteImport } from './routes/chapters/index'
import { Route as StartupsRegisterRouteImport } from './routes/startups/register'
import { Route as StartupsStartupSlugRouteImport } from './routes/startups/$startupSlug'
import { Route as PartnerCategoryPartnerTypeRouteImport } from './routes/partner-category.$partnerType'
import { Route as MeetingsRegisterRouteImport } from './routes/meetings/register'
import { Route as HubsHubIdRouteImport } from './routes/hubs/$hubId'
import { Route as FoundersConnectRouteImport } from './routes/founders/connect'
import { Route as EventsRegisterRouteImport } from './routes/events/register'
import { Route as CommunityJoinRouteImport } from './routes/community/join'
import { Route as ChaptersApplyRouteImport } from './routes/chapters/apply'
import { Route as ChaptersChapterIdRouteImport } from './routes/chapters/$chapterId'

const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HubsIndexRoute = HubsIndexRouteImport.update({
  id: '/hubs/',
  path: '/hubs/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersIndexRoute = ChaptersIndexRouteImport.update({
  id: '/chapters/',
  path: '/chapters/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsRegisterRoute = StartupsRegisterRouteImport.update({
  id: '/startups/register',
  path: '/startups/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsStartupSlugRoute = StartupsStartupSlugRouteImport.update({
  id: '/startups/$startupSlug',
  path: '/startups/$startupSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerCategoryPartnerTypeRoute =
  PartnerCategoryPartnerTypeRouteImport.update({
    id: '/partner-category/$partnerType',
    path: '/partner-category/$partnerType',
    getParentRoute: () => rootRouteImport,
  } as any)
const MeetingsRegisterRoute = MeetingsRegisterRouteImport.update({
  id: '/meetings/register',
  path: '/meetings/register',
  getParentRoute: () => rootRouteImport,
} as any)
const HubsHubIdRoute = HubsHubIdRouteImport.update({
  id: '/hubs/$hubId',
  path: '/hubs/$hubId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoundersConnectRoute = FoundersConnectRouteImport.update({
  id: '/founders/connect',
  path: '/founders/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRegisterRoute = EventsRegisterRouteImport.update({
  id: '/events/register',
  path: '/events/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityJoinRoute = CommunityJoinRouteImport.update({
  id: '/community/join',
  path: '/community/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersApplyRoute = ChaptersApplyRouteImport.update({
  id: '/chapters/apply',
  path: '/chapters/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersChapterIdRoute = ChaptersChapterIdRouteImport.update({
  id: '/chapters/$chapterId',
  path: '/chapters/$chapterId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/partners': typeof PartnersRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/chapters/apply': typeof ChaptersApplyRoute
  '/community/join': typeof CommunityJoinRoute
  '/events/register': typeof EventsRegisterRoute
  '/founders/connect': typeof FoundersConnectRoute
  '/hubs/$hubId': typeof HubsHubIdRoute
  '/meetings/register': typeof MeetingsRegisterRoute
  '/partner-category/$partnerType': typeof PartnerCategoryPartnerTypeRoute
  '/startups/$startupSlug': typeof StartupsStartupSlugRoute
  '/startups/register': typeof StartupsRegisterRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/hubs/': typeof HubsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/partners': typeof PartnersRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/chapters/apply': typeof ChaptersApplyRoute
  '/community/join': typeof CommunityJoinRoute
  '/events/register': typeof EventsRegisterRoute
  '/founders/connect': typeof FoundersConnectRoute
  '/hubs/$hubId': typeof HubsHubIdRoute
  '/meetings/register': typeof MeetingsRegisterRoute
  '/partner-category/$partnerType': typeof PartnerCategoryPartnerTypeRoute
  '/startups/$startupSlug': typeof StartupsStartupSlugRoute
  '/startups/register': typeof StartupsRegisterRoute
  '/chapters': typeof ChaptersIndexRoute
  '/events': typeof EventsIndexRoute
  '/hubs': typeof HubsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/partners': typeof PartnersRoute
  '/chapters/$chapterId': typeof ChaptersChapterIdRoute
  '/chapters/apply': typeof ChaptersApplyRoute
  '/community/join': typeof CommunityJoinRoute
  '/events/register': typeof EventsRegisterRoute
  '/founders/connect': typeof FoundersConnectRoute
  '/hubs/$hubId': typeof HubsHubIdRoute
  '/meetings/register': typeof MeetingsRegisterRoute
  '/partner-category/$partnerType': typeof PartnerCategoryPartnerTypeRoute
  '/startups/$startupSlug': typeof StartupsStartupSlugRoute
  '/startups/register': typeof StartupsRegisterRoute
  '/chapters/': typeof ChaptersIndexRoute
  '/events/': typeof EventsIndexRoute
  '/hubs/': typeof HubsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/partners'
    | '/chapters/$chapterId'
    | '/chapters/apply'
    | '/community/join'
    | '/events/register'
    | '/founders/connect'
    | '/hubs/$hubId'
    | '/meetings/register'
    | '/partner-category/$partnerType'
    | '/startups/$startupSlug'
    | '/startups/register'
    | '/chapters/'
    | '/events/'
    | '/hubs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/partners'
    | '/chapters/$chapterId'
    | '/chapters/apply'
    | '/community/join'
    | '/events/register'
    | '/founders/connect'
    | '/hubs/$hubId'
    | '/meetings/register'
    | '/partner-category/$partnerType'
    | '/startups/$startupSlug'
    | '/startups/register'
    | '/chapters'
    | '/events'
    | '/hubs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/partners'
    | '/chapters/$chapterId'
    | '/chapters/apply'
    | '/community/join'
    | '/events/register'
    | '/founders/connect'
    | '/hubs/$hubId'
    | '/meetings/register'
    | '/partner-category/$partnerType'
    | '/startups/$startupSlug'
    | '/startups/register'
    | '/chapters/'
    | '/events/'
    | '/hubs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PartnersRoute: typeof PartnersRoute
  ChaptersChapterIdRoute: typeof ChaptersChapterIdRoute
  ChaptersApplyRoute: typeof ChaptersApplyRoute
  CommunityJoinRoute: typeof CommunityJoinRoute
  EventsRegisterRoute: typeof EventsRegisterRoute
  FoundersConnectRoute: typeof FoundersConnectRoute
  HubsHubIdRoute: typeof HubsHubIdRoute
  MeetingsRegisterRoute: typeof MeetingsRegisterRoute
  PartnerCategoryPartnerTypeRoute: typeof PartnerCategoryPartnerTypeRoute
  StartupsStartupSlugRoute: typeof StartupsStartupSlugRoute
  StartupsRegisterRoute: typeof StartupsRegisterRoute
  ChaptersIndexRoute: typeof ChaptersIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  HubsIndexRoute: typeof HubsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubs/': {
      id: '/hubs/'
      path: '/hubs'
      fullPath: '/hubs/'
      preLoaderRoute: typeof HubsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/': {
      id: '/chapters/'
      path: '/chapters'
      fullPath: '/chapters/'
      preLoaderRoute: typeof ChaptersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/register': {
      id: '/startups/register'
      path: '/startups/register'
      fullPath: '/startups/register'
      preLoaderRoute: typeof StartupsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/$startupSlug': {
      id: '/startups/$startupSlug'
      path: '/startups/$startupSlug'
      fullPath: '/startups/$startupSlug'
      preLoaderRoute: typeof StartupsStartupSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-category/$partnerType': {
      id: '/partner-category/$partnerType'
      path: '/partner-category/$partnerType'
      fullPath: '/partner-category/$partnerType'
      preLoaderRoute: typeof PartnerCategoryPartnerTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings/register': {
      id: '/meetings/register'
      path: '/meetings/register'
      fullPath: '/meetings/register'
      preLoaderRoute: typeof MeetingsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hubs/$hubId': {
      id: '/hubs/$hubId'
      path: '/hubs/$hubId'
      fullPath: '/hubs/$hubId'
      preLoaderRoute: typeof HubsHubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/founders/connect': {
      id: '/founders/connect'
      path: '/founders/connect'
      fullPath: '/founders/connect'
      preLoaderRoute: typeof FoundersConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/register': {
      id: '/events/register'
      path: '/events/register'
      fullPath: '/events/register'
      preLoaderRoute: typeof EventsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/join': {
      id: '/community/join'
      path: '/community/join'
      fullPath: '/community/join'
      preLoaderRoute: typeof CommunityJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/apply': {
      id: '/chapters/apply'
      path: '/chapters/apply'
      fullPath: '/chapters/apply'
      preLoaderRoute: typeof ChaptersApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters/$chapterId': {
      id: '/chapters/$chapterId'
      path: '/chapters/$chapterId'
      fullPath: '/chapters/$chapterId'
      preLoaderRoute: typeof ChaptersChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PartnersRoute: PartnersRoute,
  ChaptersChapterIdRoute: ChaptersChapterIdRoute,
  ChaptersApplyRoute: ChaptersApplyRoute,
  CommunityJoinRoute: CommunityJoinRoute,
  EventsRegisterRoute: EventsRegisterRoute,
  FoundersConnectRoute: FoundersConnectRoute,
  HubsHubIdRoute: HubsHubIdRoute,
  MeetingsRegisterRoute: MeetingsRegisterRoute,
  PartnerCategoryPartnerTypeRoute: PartnerCategoryPartnerTypeRoute,
  StartupsStartupSlugRoute: StartupsStartupSlugRoute,
  StartupsRegisterRoute: StartupsRegisterRoute,
  ChaptersIndexRoute: ChaptersIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  HubsIndexRoute: HubsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
