/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartupsRegisterRouteImport } from './routes/startups/register'
import { Route as CommunityJoinRouteImport } from './routes/community/join'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartupsRegisterRoute = StartupsRegisterRouteImport.update({
  id: '/startups/register',
  path: '/startups/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityJoinRoute = CommunityJoinRouteImport.update({
  id: '/community/join',
  path: '/community/join',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/community/join': typeof CommunityJoinRoute
  '/startups/register': typeof StartupsRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/community/join': typeof CommunityJoinRoute
  '/startups/register': typeof StartupsRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/community/join': typeof CommunityJoinRoute
  '/startups/register': typeof StartupsRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/community/join' | '/startups/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/community/join' | '/startups/register'
  id: '__root__' | '/' | '/community/join' | '/startups/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CommunityJoinRoute: typeof CommunityJoinRoute
  StartupsRegisterRoute: typeof StartupsRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/startups/register': {
      id: '/startups/register'
      path: '/startups/register'
      fullPath: '/startups/register'
      preLoaderRoute: typeof StartupsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/join': {
      id: '/community/join'
      path: '/community/join'
      fullPath: '/community/join'
      preLoaderRoute: typeof CommunityJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CommunityJoinRoute: CommunityJoinRoute,
  StartupsRegisterRoute: StartupsRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
